import '../style/globals.css'
import { Inter } from 'next/font/google'
import { Acme } from 'next/font/google'
import {Outfit} from 'next/font/google'
import {Alatsi} from 'next/font/google'


import Header from '@/components/header'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })
const acme = Acme({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

const outfit = Outfit({
  weight: ['800'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

const alatsi = Alatsi({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Lanstur Freelance Web',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={alatsi.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}

